name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - master # Tukar ke 'master' jika branch utama GitHub anda bernama master

jobs:
  web-deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/